Site/Fleamart/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Main.urls', namespace='Main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Site/Main/urls.py
from django.urls import path
from  . import views


app_name = 'Main'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

Site/Main/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name  = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields=['name']),]
        verbose_name = 'category'
        verbose_name_plural ='categories'

    def __str__(self) -> str:
        return self.name
    
    def get_absolute_url(self):
        return reverse('Main:product_list_by_category', args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
            ]
        
    def _str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('Main:product_detail', args=[self.id, self.slug])

Site/cart/models.py
from django.db import models

# Create your models here.

Site/Main/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'Main/product/list.html', {
        'category':category,
        'categories': categories,
        'products': products
    })

def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    return render(request, 'Main/product/detail.html', {'product':product})

Site/cart/views.py
from django.shortcuts import render

# Create your views here.

Site/Main/templates/Main/base.html
{%load static%}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="/static/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@40,100,0,-25" />
    <title>Learn_bootstrap!</title>
  </head>
  <body>

    <div class="container-md">
      <!-- new nav-section -->
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#"><img src="/media/ui/bootstrap-logo.svg" alt="" width="30" height="24">FleaMart</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Store</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Summer-Deals
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="#">season</a></li>
                  <li><a class="dropdown-item" href="#">shorts</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Kids-wear</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link " href="#" tabindex="-1" aria-disabled="false">After Sales</a>
              </li>
            </ul>
            <form class="d-flex me-5">
              <div class="input-group flex-wrap">
                <input type="search" class="form-control " placeholder="Search for products here." aria-label="Search" aria-describedby="addon-wrapping">
                <button class="btn btn-outline-success"  type="submit" id="addon-wrapping"><span><i class="bi bi-search"></i></span></i></button>
              </div>
            </form>
            <div class="personalized">
              <span class="ms-5 fs-1 material-symbols-outlined">person</span>
              <span class="m-2 fs-2 material-symbols-outlined">favorite</i></span>
              <span class="m-2 fs-2 ms-1 material-symbols-outlined">shopping_cart</i></span>
            </div>
          </div>
        </div>
      </nav>

      <!-- carousel-section -->
      {%block content%}
      {%endblock content%}
      
      <div class="container footer bg-dark text-light">
        <div class="container px-4 py-5" id="icon-grid">
      
          <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4 py-5">
            <div class="col d-flex align-items-start">
              <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#bootstrap"/></svg>
              <div>
                <h4 class="fw-bold mb-0">Shop</h4>
                <ul class="list-unstyled text-sm pt-2 pt-lg-0">
                  <li class="mb-2"> <a class="text-muted text-dark-hover text-decoration-none" href="#">For Women</a></li>
                  <li class="mb-2"> <a class="text-muted text-dark-hover text-decoration-none" href="#">For Men</a></li>
                  <li class="mb-2"> <a class="text-muted text-dark-hover text-decoration-none" href="#">Stores</a></li>
                  <li class="mb-2"> <a class="text-muted text-dark-hover text-decoration-none" href="#">Our Blog</a></li>
                  <li class="mb-2"> <a class="text-muted text-dark-hover text-decoration-none" href="#">Shop</a></li>
                </ul>
              </div>
            </div>
            <div class="col d-flex align-items-start">
              <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#cpu-fill"/></svg>
              <div>
                <h4 class="fw-bold mb-0">Company</h4>
                <ul class="list-unstyled text-sm pt-2 pt-lg-0">
                  <li class="mb-2"> <a class="text-muted text-dark-hover text-decoration-none" href="#">Login</a></li>
                  <li class="mb-2"> <a class="text-muted text-dark-hover text-decoration-none" href="#">Register</a></li>
                  <li class="mb-2"> <a class="text-muted text-dark-hover text-decoration-none" href="#">Wishlist</a></li>
                  <li class="mb-2"> <a class="text-muted text-dark-hover text-decoration-none" href="#">Our Products</a></li>
                  <li class="mb-2"> <a class="text-muted text-dark-hover text-decoration-none" href="#">Checkouts</a></li>
                </ul>
              </div>
            </div>
            <div class="col d-flex align-items-start">
              <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#calendar3"/></svg>
              <div>
                <h4 class="fw-bold mb-0">Your account</h4>
                <ul class="list-unstyled text-sm pt-2 pt-lg-0">
                  <li class="mb-2"> <a class="text-muted text-dark-hover text-decoration-none" href="#">Login</a></li>
                  <li class="mb-2"> <a class="text-muted text-dark-hover text-decoration-none" href="#">Register</a></li>
                  <li class="mb-2"> <a class="text-muted text-dark-hover text-decoration-none" href="#">Wishlist</a></li>
                  <li class="mb-2"> <a class="text-muted text-dark-hover text-decoration-none" href="#">Our Products</a></li>
                  <li class="mb-2"> <a class="text-muted text-dark-hover text-decoration-none" href="#">Checkouts</a></li>
                </ul>
              </div>
            </div>
            <div class="col d-flex align-items-start">
              <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#home"/></svg>
              <div>
                <h4 class="fw-bold mb-0">About</h4>
                <ul class="list-unstyled text-sm pt-2 pt-lg-0">
                  <li class="mb-2"> <a class="text-muted text-dark-hover text-decoration-none" href="#">Login</a></li>
                  <li class="mb-2"> <a class="text-muted text-dark-hover text-decoration-none" href="#">Register</a></li>
                  <li class="mb-2"> <a class="text-muted text-dark-hover text-decoration-none" href="#">Wishlist</a></li>
                  <li class="mb-2"> <a class="text-muted text-dark-hover text-decoration-none" href="#">Our Products</a></li>
                  <li class="mb-2"> <a class="text-muted text-dark-hover text-decoration-none" href="#">Checkouts</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="row justify-content-between align-items-center text-sm text-gray-500 ">
            <div class="col-lg-4 align-self-end text-muted"><p>@2023 calvincetom.tech. All rights reserved.</p></div>
            <div class="col-lg-8 ">
              <ul class="list-inline list-unstyled mb-0 mt-2 mt-md-0 text-center text-lg-end">
                <li class="list-inline-item"><a href="http://" class="link text-muted" >Terms and conditions</a></li>
                <li class="list-inline-item"><a href="http://" class="link text-muted">privacy and cookies</a></li>
                <li class="list-inline-item"><a href="http://" class="link text-muted">data policy</a></li>
              </ul>
            </div>
          </div>
      </div>

    </div>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

Site/Main/templates/Main/product/detail.html
{% extends 'Main/base.html' %}
{%load static%}

{%block title%}
{{ product.name }}
{%endblock%}
{% block content %}
<div class="card-section fw-bold">
  <div class="row row-cols-1 row-cols-md-5 g-4 ">
    <div class="col">
      <div class="card h-100 border-0">
        <img src="{% if product.image %}{{ product.image.url }}{%else%} {%static 'img/no_image.png'%}{%endif%}" class="card-img-top" alt="...">
        <div class="card-body">
          <p class="card-text">{{product.name}}</p>
        </div>
        <div class="card-footer">
          <small class="text-muted text-decoration-line-through">£{{product.price}}</small><small class="ms-3 text-dark">£{{product.price}}</small>
        </div>
        <p class="card-text">{{ product.description|linebreaks }}</p>
      </div>
    </div>
  </div>
</div>

{% endblock %}

Site/Main/templates/Main/product/list.html
{%extends 'Main/base.html' %}
{%load static%}

{%block title%}
    {%if category%}{{ category.name }}{%else%}Products{%endif%}
{%endblock title%}

{%block content%}


    <!-- carousel-section -->
    <div class="carousel-section mb-3">
        <div id="carouselCaptions" class="carousel carousel-dark slide" data-bs-ride="carousel">
          <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
          </div>
          <div class="carousel-inner">
            <div class="carousel-item active overflow-auto">
              <div class="carousel-caption d-flex d-md-block">
                <h5>Blouses & Skirts</h5>
                <p class="fw-bolder">Get ready for summer with our stylish new arrivals. <span class="text-primary fs-4"><i class="bi bi-bookmark-check-fill"></i></span></p>
               
                <button type="button" class="d-flex flex-row-reverse btn btn-dark">Discover More</button>
              </div>
              <img src="/media/ui/lady.jpg" class="d-flex w-50 " alt="...">
            </div>
            <div class="carousel-item">
              <div class="carousel-caption d-flex d-md-block">
                <h5>Shoes and Trousers</h5>
                <p class="fw-bold">Don't miss out on our special sale. Limited time offer!</p>
                <button type="button" class="btn btn-dark">Discover More</button>
              </div>
              <img src="media/ui/manshop.jpg" class="d-flex w-50" alt="...">
            </div>
            <div class="carousel-item">
              <div class="carousel-caption d-flex d-md-block">
                <h5>Blouses and Shorts</h5>
                <p class="fw-bolder">Summer Vibe sale.<span class="text-success fs-4"><i class="bi bi-tag-fill"></i></span></p>
                
                <button type="button" class="d-flex flex-row-reverse btn btn-dark">Discover More</button>
              </div>
              <img src="media/ui/fashion.jpg" class="d-flex w-50" alt="...">
            </div>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselCaptions" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselCaptions" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
    </div>
        <!-- minimal-hero -->
    <div class="minimal-hero">
        <div class="row">
            <div class="col text-center mb-5 mx-auto">
            <p class="mb-5 fs-1">New arrivals</p>
            <p class=" text-muted">One morning, when Gregor Samsa woke from troubled dreams, <br> found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, <br>and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections</p>
            </div>
        </div>
    </div>

        <!-- product link contanier -->
    <div class="product-link container">
    <div class="row justify-content-between align-items-center mb-4">
        <div class="col-8 col-sm">
        <ul class="list-inline text-center text-sm-start fw-bold">
            <li class="list-inline-item"><a class="text-dark text-decoration-none" href="{%url 'Main:product_list' %}">All Products </a></li>
            {%for c in categories%}
            <li class="list-inline-item">
            <a class="text-muted text-decoration-none" href="{{c.get_absolute_url }}">{{c.name}}</a>
            </li>
            {% endfor %}
        </ul>
        </div>
        <div class="col-4 text-end"><a href="{%url 'Main:product_list' %}" class="btn btn-dark ">All Products</a></div>
    </div>
    
    <div class="card-section fw-bold">
        <p>{% if category %}{{ category.name }}{% else %}Products{% endif %}</p>
        <div class="row row-cols-1 row-cols-md-5 g-4 ">
            {% for product in products %}
            <div class="col">
                <div class="card h-100 border-0">
                    <a href="{{ product.get_absolute_url }}" class="no-text-decoration">
                        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" class="card-img-top" alt="">
                    </a>
                <div class="card-body">
                    <p class="card-text"><a href="{{ product.get_absolute_url }}" class="no-text-decoration">{{ product.name }}</a></p>
                </div>
                <div class="card-footer">
                    <small class="text-muted text-decoration-line-through">£{{ product.price }}</small><small class="ms-3 text-dark">£{{ product.price }}</small>
                </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    
    <!-- minimal-hero-2 -->
    <div class="minimal-hero-2">
        <div class="row mt-5">
          <div class="col-8">
            <p class=" text-danger text-uppercase fs-5 ms-5 mt-5 mb-4">Deal of the Week</p>
            <p class=" fw-bold fs-1 ms-5 ">Cool Jumpers</p>
            <button type="button" class="btn btn-success ms-5">£50 off</button>
            <div class="container">
              <div class="row bg-light m-4 justify-content-center fw-bold">
                <div class="timer col text-center fs-1 ">
                  13 <br><span class="text-muted fs-4">Days</span>
                </div>
                <div class="timer col text-center fs-1">
                  17 <br><span class="text-muted fs-4">Hours</span>
                </div>
                <div class="timer col text-center fs-1">
                  36 <br><span class="text-muted fs-4">Minutes</span>
                </div>
                <div class="timer col text-center fs-1">
                  15 <br><span class="text-muted fs-4">Seconds</span>
                </div>
              </div>
            </div>
            <button type="button" class="btn btn-outline-dark ms-5">Buy Now</button>
            <div class="d-flex justify-content-center">
              <div class="text-center">
                <!-- Your text content goes here -->
                <h1><span><i class="bi bi-caret-down-fill"></i></span></h1>
                <p> <button type="button" class="btn btn-dark">50% Discount</button></p>
              </div>
            </div>
            
          </div>
          <div class="col-4 align-contents-end">
            <img class="d-flex  w-100" src="media/ui/adam-diji.jpg" srcset="">
          </div>
        </div>
      </div>

      <!-- custom-cards -->
      <div class="container">
        <div class="container px-4 py-5" id="custom-cards">
          <div class="row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5">
            <div class="col">
              <div class="card card-cover h-100 overflow-hidden text-white bg-light rounded-5 shadow-lg" style="background-image: url('./media/ui/custom-2.jpg');">
                <div class="d-flex flex-column h-100 p-5 pb-3 text-success text-shadow-1">
                  <h2 class="pt-5 mt-5 mb-4 display-7 lh-1 fw-bold">Value for money</h2>
                  <ul class="d-flex list-unstyled mt-auto">
                    <li class="me-auto">
                      <img src="https://github.com/twbs.png" alt="Bootstrap" width="32" height="32" class="rounded-circle border border-white">
                    </li>
                    <li class="d-flex align-items-center me-3">
                      <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#geo-fill"/></svg>
                      <small>Earth</small>
                    </li>
                    <li class="d-flex align-items-center">
                      <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#calendar3"/></svg>
                      <small>3d</small>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
      
            <div class="col">
              <div class="card card-cover h-100 overflow-hidden text-white bg-light rounded-5 shadow-lg" style="background-image: url('./media/ui/custom-1.jpg');">
                <div class="d-flex flex-column h-100 p-5 pb-3 text-danger text-shadow-1">
                  <h2 class="pt-5 mt-5 mb-4 display-7 lh-1 fw-bold">Just a <span class="text-dark">click</span> away</h2>
                  <ul class="d-flex list-unstyled mt-auto">
                    <li class="me-auto">
                      <img src="https://github.com/twbs.png" alt="Bootstrap" width="32" height="32" class="rounded-circle border border-white">
                    </li>
                    <li class="d-flex align-items-center me-3">
                      <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#geo-fill"/></svg>
                      <small>Pakistan</small>
                    </li>
                    <li class="d-flex align-items-center">
                      <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#calendar3"/></svg>
                      <small>4d</small>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
      
            <div class="col">
              <div class="card card-cover h-100 overflow-hidden text-white bg-light rounded-5 shadow-lg" style="background-image: url('./media/ui/custom-3.jpg');">
                <div class="d-flex flex-column h-100 p-5 pb-3 text-success text-shadow-1">
                  <h2 class="pt-5 mt-5 mb-4 display-7 lh-1 fw-bold">Faster transactions</h2>
                  <ul class="d-flex list-unstyled mt-auto">
                    <li class="me-auto">
                      <img src="https://github.com/twbs.png" alt="Bootstrap" width="32" height="32" class="rounded-circle border border-white">
                    </li>
                    <li class="d-flex align-items-center me-3">
                      <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#geo-fill"/></svg>
                      <small>California</small>
                    </li>
                    <li class="d-flex align-items-center">
                      <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#calendar3"/></svg>
                      <small>5d</small>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
{%endblock content%}